project:
  type: book

book:
  title: "Proyectos de Bases de Datos"
  author: "Pedro Villa Casas"
  date: "7/10/2015"
  chapters:
    - index.qmd
    - Agroquimicos.md
    - Bichos_de_bolsillo.md
    - Comedor_colegio.md
    - ./Conquistadores/Conquistadores.md
    - ./Pawfect_Care/Pawfect_Care.md
    - ./Salud y Vida/Salud y Vida.md

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt