project:
  type: book

book:
  title: "Proyectos de Bases de Datos"
  author: "Pedro Villa Casas"
  date: "7/10/2015"
  chapters:
    - index.qmd
    - ./Agroquimicos/Agroquimicos.md
    - ./Bichos/Bichos_de_bolsillo.md
    - ./Comedor/Comedor_colegio.md
    - ./Conquistadores/Conquistadores.md
    - ./Inmobiliaria/Morshu_Estates.md
    - ./Pawfect_Care/Pawfect_Care.md
    - ./MasterBall/MasterBall_Tournaments.md
    - ./MyBeat/README.md
    - ./Salud y Vida/Salud y Vida.md
    - ./TrumpetWare/TrumpetWare.md

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt